/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_net.h"
#include "isr_tx_net.h"
#include "isr_rx_net.h"
#include "PTZ_X_aliases.h"
#include "PTZ_X.h"
#include "Timer_1.h"
#include "isr_timer.h"
#include "MSR_LOW_aliases.h"
#include "MSR_LOW.h"
#include "STR2_aliases.h"
#include "STR2.h"
#include "SWITCH_2_LOW_aliases.h"
#include "SWITCH_2_LOW.h"
#include "SWITCH_1_LOW_aliases.h"
#include "SWITCH_1_LOW.h"
#include "SWITCH_2_HIGH_aliases.h"
#include "SWITCH_2_HIGH.h"
#include "STR1_aliases.h"
#include "STR1.h"
#include "MSR_HIGH_aliases.h"
#include "MSR_HIGH.h"
#include "SWITCH_1_HIGH_aliases.h"
#include "SWITCH_1_HIGH.h"
#include "ADC.h"
#include "PTZ_Y_aliases.h"
#include "PTZ_Y.h"
#include "CAR_Y_aliases.h"
#include "CAR_Y.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "CAR_X_aliases.h"
#include "CAR_X.h"
#include "BATTERY_aliases.h"
#include "BATTERY.h"
#include "LED_2_aliases.h"
#include "LED_2.h"
#include "LED_3_aliases.h"
#include "LED_3.h"
#include "CAR_SPEED_aliases.h"
#include "CAR_SPEED.h"
#include "WARNING_GREEN_aliases.h"
#include "WARNING_GREEN.h"
#include "WARNING_BLUE_aliases.h"
#include "WARNING_BLUE.h"
#include "WARNING_RED_aliases.h"
#include "WARNING_RED.h"
#include "UART_net_IntClock.h"
#include "ADC_SAR.h"
#include "ADC_IntClock.h"
#include "ADC_TempBuf_dma.h"
#include "ADC_FinalBuf_dma.h"
#include "ADC_IRQ.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

