/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_net.h"
#include "isr_tx_net.h"
#include "isr_rx_net.h"
#include "Beep_aliases.h"
#include "Beep.h"
#include "KEY_UP_aliases.h"
#include "KEY_UP.h"
#include "KEY_DOWN_aliases.h"
#include "KEY_DOWN.h"
#include "KEY_LEFT_aliases.h"
#include "KEY_LEFT.h"
#include "KEY_RIGHT_aliases.h"
#include "KEY_RIGHT.h"
#include "KEY_SPEED_LOW_aliases.h"
#include "KEY_SPEED_LOW.h"
#include "Timer_1.h"
#include "isr_timer.h"
#include "PTZ_UP_aliases.h"
#include "PTZ_UP.h"
#include "PTZ_DOWN_aliases.h"
#include "PTZ_DOWN.h"
#include "PTZ_LEFT_aliases.h"
#include "PTZ_LEFT.h"
#include "PTZ_RIGHT_aliases.h"
#include "PTZ_RIGHT.h"
#include "KEY_SPEED_HIGH_aliases.h"
#include "KEY_SPEED_HIGH.h"
#include "LED_START_aliases.h"
#include "LED_START.h"
#include "LED_LEFT_LOW_aliases.h"
#include "LED_LEFT_LOW.h"
#include "LED_DOWN_LOW_aliases.h"
#include "LED_DOWN_LOW.h"
#include "LED_UP_LOW_aliases.h"
#include "LED_UP_LOW.h"
#include "LED_RIGHT_LOW_aliases.h"
#include "LED_RIGHT_LOW.h"
#include "LED_UP_HIGH_aliases.h"
#include "LED_UP_HIGH.h"
#include "LED_DOWN_HIGH_aliases.h"
#include "LED_DOWN_HIGH.h"
#include "LED_LEFT_HIGH_aliases.h"
#include "LED_LEFT_HIGH.h"
#include "LED_RIGHT_HIGH_aliases.h"
#include "LED_RIGHT_HIGH.h"
#include "UART_net_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

